sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t utkarshsawant/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true utkarshsawant/docker-react npm run test